name: Create Draft Release

permissions:
    contents: write

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download local lib JARs
              run: |
                    mkdir -p libs
                    curl -L -o libs/physics-mod-3.0.24-mc-1.21.1-fabric.jar \
                        "https://cdn.modrinth.com/data/Xy8aRQKS/versions/R3aluipj/physics-mod-3.0.24-mc-1.21.1-fabric.jar"
                    curl -L -o libs/resourcefullib-fabric-1.21-3.0.12.jar \
                        "https://cdn.modrinth.com/data/G1hIVOrD/versions/Hf91FuVF/resourcefullib-fabric-1.21-3.0.12.jar"
                    curl -L -o libs/yet_another_config_lib_v3-3.6.5+1.21.1-fabric.jar \
                        "https://cdn.modrinth.com/data/1eAoo2KR/versions/BMVCssHI/yet_another_config_lib_v3-3.6.5%2B1.21.1-fabric.jar"

            - name: Validate Gradle wrapper
              uses: gradle/actions/wrapper-validation@v4
            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "25"
                  distribution: "microsoft"
            - name: Make Gradle wrapper executable
              run: chmod +x ./gradlew
            - name: Build
              run: ./gradlew build
            - name: capture build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Artifacts
                  path: build/libs/

            - name: Extract version without v prefix
              id: version
              run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

            - name: Create draft release and upload assets
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: LT x EC ${{ github.ref_name }}
                  draft: true
                  prerelease: false
                  body: "-"
                  files: |
                      build/libs/wildlight-${{ steps.version.outputs.VERSION }}.jar
                      build/libs/wildlight-${{ steps.version.outputs.VERSION }}-javadoc.jar
                      build/libs/wildlight-${{ steps.version.outputs.VERSION }}-sources.jar
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
